config/routes.rb
Rails.application.routes.draw do
  if Rails.application.config.x.inactive_service
    match "(*any)", to: "pages#inactive_service", via: :all
  end

  root to: 'calculations#new', as: :new_calculation

  post 'results', to: 'calculations#results', as: :results
  get 'results', to: redirect('/')

  get '/privacy-notice', to: 'pages#privacy_notice'
  get '/accessibility-statement', to: 'pages#accessibility_statement'
  get '/terms-and-conditions', to: 'pages#terms_and_conditions'

  get '/healthcheck', to: proc { [200, {}, ['OK']] }

  scope via: :all do
    get '/404', to: 'errors#not_found'
    get '/422', to: 'errors#unprocessable_entity'
    get '/429', to: 'errors#too_many_requests'
    get '/500', to: 'errors#internal_server_error'
  end
end

app/models/area.rb
class Area < BaseModel
  attr_accessor :id, :name

  def self.find(id)
    found = all_areas[id]
    return nil unless found

    new(id:, name: found)
  end

  def self.all_areas
    Rails.configuration.x.calculator.areas
  end
  private_class_method :all_areas
end

app/models/calculation_form.rb
class CalculationForm < Form
  attribute :area_id, :string
  attribute :pay_band_id, :string

  validates :pay_band_id, :area_id, presence: true

  validates :pay_band_id, inclusion: { in: proc { PayBand.pluck(:id, &:to_s) }, message: :invalid }
  validates :area_id, inclusion: { in: proc { Area.pluck(:id, &:to_s) }, message: :invalid }

  def area
    Area.find(id: area_id.to_sym)
  end

  def pay_band
    PayBand.find(id: pay_band_id.to_sym)
  end

  def salary_figure
    SalaryFigures.find(area:, pay_band:)
  end
end

app/models/form.rb
class Form
  include ActiveModel::Model
  include ActiveModel::Attributes
  include ActiveModel::AttributeAssignment
end

app/models/pay_band.rb
PayBand = Struct.new(:id, :name, :type)

class << PayBand
  delegate :find, :all, :pluck, to: :store

  def store
    @store ||= StructStore.new(self)
  end
end

app/models/salary_figures.rb
SalaryFigures = Struct.new(:area, :pay_band, :type, :current, :future, :increase, :increase_percentage) do
  def range?
    type == :range
  end
end

class << SalaryFigures
  delegate :find, :all, to: :store

  def store
    @store ||= StructStore.new(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include HttpAuthConcern

  skip_forgery_protection

  default_form_builder(GOVUKDesignSystemFormBuilder::FormBuilder)
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
  def new
  end

  def results
    form.assign_attributes(calculation_params)

    if form.valid?
      @presenter = SalaryPresenter.new(form.salary_figure)
      render :results
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def calculation_params
    params.require(:calculation_form).permit(:area_id, :pay_band_id)
  end

  def form
    @form ||= CalculationForm.new
  end
  helper_method :form
end

app/controllers/concerns/http_auth_concern.rb
module HttpAuthConcern
  extend ActiveSupport::Concern

  included do
    if ENV["HTTP_USERNAME"].present? && ENV["HTTP_PASSWORD"].present?
      http_basic_authenticate_with(
        name: ENV.fetch("HTTP_USERNAME"),
        password: ENV.fetch("HTTP_PASSWORD")
      )
    end
  end
end

app/controllers/errors_controller.rb
# frozen_string_literal: true
class ErrorsController < ApplicationController
  def not_found
    render 'not_found', status: :not_found
  end

  def unprocessable_entity
    render 'unprocessable_entity', status: :unprocessable_entity
  end

  def too_many_requests
    render 'too_many_requests', status: :too_many_requests
  end

  def internal_server_error
    render 'internal_server_error', status: :internal_server_error
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def privacy_notice
  end

  def accessibility_statement
  end

  def terms_and_conditions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calculations/_form.html.slim
= form_with model: form, data: { turbo: false }, url: results_path do |f|

  = f.govuk_error_summary

  = f.govuk_collection_select :pay_band_id,
    PayBand.all,
    :id,
    :name,
    label: { text: t('questions.current_pay_band.label'), size: 's' },
    options: { include_blank: t('questions.no_option.label') }

  = f.govuk_radio_buttons_fieldset(:area_id,
      legend: { size: 's', text: t('questions.area.label') },
      hint: { text: t('questions.area.hint'), size: 's' }) do
    - Area.all.each_with_index do |area, index|
      - if index == Area.all.count - 1
        = f.govuk_radio_divider
      = f.govuk_radio_button :area_id, area.id, label: { text: area.name }

  = f.govuk_submit t('questions.submit.label')

app/views/calculations/new.html.slim
h1.govuk-heading-xl
  = t('questions.heading')

= render 'calculations/form'

app/views/calculations/results.html.slim
= govuk_panel(title_text: @presenter.primary_text, text: @presenter.secondary_text)

p.govuk-body
  = t('results.description')

p.govuk-body
  = t('results.funding_html')

h1.govuk-heading-m
  = t('results.summary.title')

= govuk_summary_list(actions: false) do |summary_list|
  - summary_list.with_row do |row|
    - row.with_key { t('questions.current_pay_band.label') }
    - row.with_value { form.pay_band.name }

  - summary_list.with_row do |row|
    - row.with_key { t('questions.area.label') }
    - row.with_value { form.area.name }

p.govuk-body
  = t('results.start_again.text')

= link_to(t('results.start_again.label'), new_calculation_path, class: "govuk-button govuk-button--secondary")

app/views/layouts/application.html.slim
doctype html
html lang='en' class='govuk-template'
  head
    title =[yield(:page_title).presence, t('service.name')].compact.join(' - ')

    = csrf_meta_tags
    = csp_meta_tag

    = tag.meta name: 'viewport', content: 'width=device-width, initial-scale=1, viewport-fit=cover'
    = tag.meta property: 'og:image', content: asset_path('images/govuk-opengraph-image.png')
    = tag.meta name: 'theme-color', content: '#0b0c0c'
    = tag.meta name: 'robots', content: 'noindex,nofollow'
    = favicon_link_tag asset_path('images/favicon.ico')
    = favicon_link_tag asset_path('images/govuk-icon-mask.svg'), rel: 'mask-icon', type: 'image/svg+xml', color: '#0b0c0c'
    = favicon_link_tag asset_path('images/govuk-icon-180.png'), rel: 'apple-touch-icon', type: 'image/png', sizes: '180x180'
    = favicon_link_tag asset_path('images/govuk-icon-192.png'), rel: 'apple-touch-icon', type: 'image/png', sizes: '192x192'
    = favicon_link_tag asset_path('images/govuk-icon-512.png'), rel: 'apple-touch-icon', type: 'image/png', sizes: '512x512'

    = stylesheet_link_tag 'application', data: { turbo_track: 'reload' }
    = javascript_include_tag 'application', data: { turbo_track: 'reload' }, defer: true

  body.govuk-template__body
    javascript:
      document.body.className = ((document.body.className) ? document.body.className + ' js-enabled' : 'js-enabled');

    = govuk_skip_link

    = govuk_header(homepage_url: 'https://www.gov.uk', service_name: t('service.name'), service_url: '/')

    .govuk-width-container
      - unless Rails.application.config.environment_name.production?
        = govuk_phase_banner(tag: { text: 'Warning', colour: 'pink' }, text: 'This is a test environment and does not contain nor produce any real or accurate data')

      .govuk-main-wrapper
        .govuk-grid-row
          .govuk-grid-column-two-thirds
            = yield

  ruby:
    footer_links = {
      'Privacy notice' => privacy_notice_path,
      'Accessibility statement' => accessibility_statement_path,
      'Terms and conditions' => terms_and_conditions_path
    }
  = govuk_footer(meta_items: footer_links)

app/views/pages/accessibility_statement.html.slim
- content_for :page_title_prefix do
  | Accessibility statement

markdown:

  # **Accessibility statement**
  {: .govuk-heading-xl}

  This service is run by the Department for Education (DfE).

  DfE is committed to making its websites accessible, in accordance with the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018.

  We want as many people as possible to be able to use this service.

  You should be able to:

  * change colours, contrast levels and fonts
  * zoom in up to 300% without the text spilling off the screen
  * navigate most of the service using just a keyboard
  * navigate most of the service using speech recognition software
  * listen to most of the content on this service using a screen reader (including the most recent versions of JAWS, NVDA and VoiceOver)
  {: .govuk-list.govuk-list--bullet }

  We’ve also made the text on the service as simple as possible to understand.

  ## How accessible this service is
  {: .govuk-heading-l}

  This service is fully compliant with the [Web Content Accessibility Guidelines version (WCAG) 2.1](https://www.w3.org/TR/WCAG21/){: .govuk-link}.

  We are constantly improving the service and run accessibility audits during each new phase of development.

  ## Report accessibility problems
  {: .govuk-heading-l}

  [Contact DfE](https://form.education.gov.uk/service/Contact_the_Department_for_Education){: .govuk-link} if you find any problems that are not listed on this page or think we’re not meeting accessibility requirements.

  ## Enforcement procedure
  {: .govuk-heading-l}

  The Equality and Human Rights Commission (EHRC) is responsible for enforcing the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018 (the ’accessibility regulations’).

  If you’re not happy with how we respond to your complaint, [contact the Equality Advisory and Support Service (EASS)](https://www.equalityadvisoryservice.com/){: .govuk-link}.

  ## How we tested this website
  {: .govuk-heading-l}

  This website was last tested in June 2023. The test was carried out by an internal team at DFE.

  The team tested various combinations of the following for both desktop and mobile and tablet users:

  * assistive technologies (for example, screen magnifiers, screen readers and speech recognition tools)
  * different browsers (IE11, Firefox, Safari, Chrome)
  * manual testing
  {: .govuk-list.govuk-list--bullet }

  This statement was last updated on 3 July 2023.

app/views/pages/accessibility_statement.slim
- content_for :page_title_prefix do
  | Accessibility statement

markdown:

  # **Accessibility statement**
  {: .govuk-heading-xl}

  This service is run by the Department for Education (DfE).

  DfE is committed to making its websites accessible, in accordance with the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018.

  We want as many people as possible to be able to use this service.

  You should be able to:

  * change colours, contrast levels and fonts
  * zoom in up to 300% without the text spilling off the screen
  * navigate most of the service using just a keyboard
  * navigate most of the service using speech recognition software
  * listen to most of the content on this service using a screen reader (including the most recent versions of JAWS, NVDA and VoiceOver)
  {: .govuk-list.govuk-list--bullet }

  We've also made the text on the service as simple as possible to understand.

  ## How accessible this service is
  {: .govuk-heading-l}

  This service is fully compliant with the [Web Content Accessibility Guidelines version (WCAG) 2.1](https://www.w3.org/TR/WCAG21/){: .govuk-link}.

  We are constantly improving the service and run accessibility audits during each new phase of development.

  ## Report accessibility problems
  {: .govuk-heading-l}

  [Contact DfE](https://form.education.gov.uk/service/Contact_the_Department_for_Education){: .govuk-link} if you find any problems that are not listed on this page or think we're not meeting accessibility requirements.

  ## Enforcement procedure
  {: .govuk-heading-l}

  The Equality and Human Rights Commission (EHRC) is responsible for enforcing the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018 (the 'accessibility regulations').

  If you're not happy with how we respond to your complaint, [contact the Equality Advisory and Support Service (EASS)](https://www.equalityadvisoryservice.com/){: .govuk-link}.

  ## How we tested this website
  {: .govuk-heading-l}

  This website was last tested in June 2023. The test was carried out by an internal team at DFE.

  The team tested various combinations of the following for both desktop and mobile and tablet users:

  * assistive technologies (for example, screen magnifiers, screen readers and speech recognition tools)
  * different browsers (IE11, Firefox, Safari, Chrome)
  * manual testing
  {: .govuk-list.govuk-list--bullet }

  This statement was last updated on 3 July 2023.

app/views/pages/inactive_service.html.slim
- content_for :page_title_prefix, "Inactive service"

h1.govuk-heading-l This service is not currently available

app/views/pages/privacy_notice.html.slim
- content_for :page_title_prefix do
  | Privacy notice

markdown:

  # **Privacy notice**
  {: .govuk-heading-xl}

  This privacy notice explains how the Department for Education (DfE) uses personal information on ’Calculate teacher pay’.

  Teachers and leaders can use ’Calculate teacher pay’ to see how their salary could change following the 2025 pay award.

  Visit our [personal information charter](https://www.gov.uk/government/organisations/department-for-education/about/personal-information-charter){: .govuk-link} to see the standards you can expect from DfE when we collect, hold or use your personal data.

  ## Lawful basis for processing your data
  {: .govuk-heading-l}

  DfE is the data controller for your personal data.

  Our lawful basis for collecting your personal data when you use ’Calculate teacher pay’ is ’public task’ (article 6(1)(e) UK GDPR), together with section 122 of the Education Act 2002.

  ## Data we collect
  {: .govuk-heading-l}

  We collect your Internet Protocol (IP) address when you use this service.

  ## How we use your data
  {: .govuk-heading-l}

  We will use and store your IP address to:

  * identify security and privacy threats to the service
  * make sure the service is working correctly
  * help us fix technical problems with the website
  {: .govuk-list.govuk-list--bullet }

  Your data is not used for analytics purposes.

  ## How long we keep your data
  {: .govuk-heading-l}

  DfE will keep your IP address for no longer than 30 days.

  ## Data processors
  {: .govuk-heading-l}

  A data processor is an organisation that processes your information on DfE’s behalf.

  We do not use data processors for our activities.

  ## Transferring your personal information overseas
  {: .govuk-heading-l}

  We do not store your personal information outside of the UK.

  ## Sharing your personal information
  {: .govuk-heading-l}

  We do not share your personal information when you use ’Calculate teacher pay’.

  ## Your data protection rights
  {: .govuk-heading-l}

  You have data collection rights, including the right to:

  * ask for a copy of the personal information we have about you – ’right of access’
  * ask us to change any information you think is not accurate or complete – ’right to rectification’
  * ask us to delete your personal information – ’right to erasure’
  * ask us to stop using your information – ’right to restriction of processing’
  * object to us processing your information – ’right to object to processing’
  {: .govuk-list.govuk-list--bullet }

  For more information on your rights, visit the [Information Comissioner’s Office website](https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/individual-rights/individual-rights/){: .govuk-link}.

  ## Finding out what information we have
  {: .govuk-heading-l}

  You have the right to ask for access to your personal information. This is known as a subject access request.

  [Contact DfE to make a subject access request](https://form.education.gov.uk/service/Contact_the_Department_for_Education){: .govuk-link}.

  ## How to contact us or make a complaint
  {: .govuk-heading-l}

  [Contact DfE](https://form.education.gov.uk/service/Contact_the_Department_for_Education){: .govuk-link} online or write to our data protection officer at:

  * Emma Wharram Data Protection Officer
  * Department for Education (B2.28)
  * 7 & 8 Wellington Place
  * Wellington Street
  * Leeds
  * LS1 4AW
  {: .govuk-list }

  You can also [contact the Information Comissioner’s Office](https://ico.org.uk/make-a-complaint/data-protection-complaints/data-protection-complaints){: .govuk-link} online or write to them at:

  * Information Commissioner’s Office
  * Wycliffe House
  * Water Lane
  * Wilmslow
  * Cheshire
  * SK9 5AF
  * Helpline number: 0303 123 1113.
  {: .govuk-list }

  ## Last updated
  {: .govuk-heading-l}

  This privacy notice was last updated on 24 April 2025.

  Visit this page from time to time as we may update this information.

app/views/pages/terms_and_conditions.html.slim
- content_for :page_title_prefix do
  | Terms and conditions

markdown:

  # Terms and conditions
  {: .govuk-heading-xl}

  ’Calculate teacher pay’ is a service run by the Department for Education (DfE).

  By using this service, you automatically agree to these terms and conditions in addition to the terms and conditions which apply to the use of all GOV.UK websites.

  If you do not agree to these terms and conditions, you must not use this service.

  # Disclaimer
  {: .govuk-heading-xl}

  We do not provide any guarantees, conditions or warranties that the information on this service will be:

  * current
  * secure
  * accurate
  * complete
  * reliable and always available
  * free from bugs or viruses or any other type of damaging software or malicious technology
  {: .govuk-list.govuk-list--bullet }

  You must use this service:

  * only to calculate the advisory pay point for teachers following the 2025 pay award
  * only for lawful purposes
  {: .govuk-list.govuk-list--bullet }

  You must not:

  * charge your website’s users to click on a link to any page of the service
  * use this service in a way that infringes the rights of, or restricts or inhibits the use or enjoyment of, this site by anyone else
  * say or act in a way that implies that your website is associated with this service, DfE, GOV.UK or another government department or agency
  * load our service pages into frames on your site
  * access parts of the site which are not publicly available, or any data or information that belongs or relates to a third party, without express consent
  {: .govuk-list.govuk-list--bullet }

  ## Viruses, hacking and other offences
  {: .govuk-heading-l}

  You must not:

  * introduce viruses, trojans, worms, logic bombs or any other material that may cause damage or loss to our IT systems or their content, or be malicious or technologically harmful
  * try to gain unauthorised access to this service, the server on which it is stored or any server, computer or database connected to it
  * attack this service in any way (this includes denial-of-service attacks)
  {: .govuk-list.govuk-list--bullet }

  We reserve the right to report any attacks or attempts to gain unauthorised access to this service or GOV.UK to the relevant law enforcement authorities and share information about you with them without notice.

  ## Information about you
  {: .govuk-heading-l}

  We collect information about you in accordance with our [privacy policy](./privacy-notice){: .govuk-link} but cannot guarantee that your personal data remains confidential.

  By using this service, you agree to us collecting the data outlined in our privacy policy.

  ## Validity of these terms and conditions
  {: .govuk-heading-l}

  If any of these terms and conditions are held to be invalid, unenforceable, or illegal for any reason, the remaining terms and conditions will still apply.

  ## Governing law
  {: .govuk-heading-l}

  These terms and conditions are governed by and construed in accordance with the laws of England and Wales.

  Any dispute you have which relates to these terms and conditions or your use of this service, whether contractual or non-contractual, will be subject to the exclusive jurisdiction of the courts of England and Wales (or Scotland or Northern Ireland if you are an individual in either of those jurisdictions) or, at our discretion, in any other courts having jurisdiction.

  ## Changes to these terms and conditions
  {: .govuk-heading-l}

  We check these terms and conditions regularly. We can update them at any time without notice.

  You are automatically deemed to agree to any changes if you continue to use this service after the terms and conditions have been updated.

  Last updated 24 April 2025.